export default culturaldata = [
    {
        "id":1,
        "title":"Feets on the Beats",
        "subtitle":"Group Dance",
        "image":require("./assets/culturalEventPics/grpdance.png"),
        "url":"gvhb",
        "time":"14 April 2024",
        "fee":"₹ 650",
        "prize":"₹ 52k",
        "teamSize":"5-16 members",
        "desc":"Get ready for an electrifying showcase of creativity and synchronization in our Group Dance Extravaganza! Watch as skilled dance crews compete in a thrilling competition, delivering dynamic performances that span hip-hop's infectious beats to the graceful movements of contemporary dance. Brace yourself for mesmerizing choreography, eyecatching costumes and unparalleled showmanship.",
        "deadline":"9 April 2024",
        "moredetails":"https://docs.google.com/document/d/1JdXa2beaU-cWC7peJqM1RrQeDmB0YjdQb4-ILMwE9T4/edit",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLSfHjJFcGBDtyiAW5xP5U5UjjB814Q1daRluH9q7H76EK3bA4Q/viewform"
    },
    {
        "id":2,
        "title":"Solo BeatBlaze",
        "subtitle":"Solo Dance",
        "image":require("./assets/culturalEventPics/solodance.png"),
        "url":"gvhb",
        "time":"13 April 2024",
        "fee":"₹ 200",
        "prize":"₹ 16k",
        "teamSize":"1 member",
        "desc":"Witness an ensemble of extraordinary solo dancers ignite the stage with mesmerizing performances. From hip-hop's rhythmic beats to contemporary dance's grace, each artist captivates with distinctive style, breathtaking choreography and sensational showmanship. Join us for a night of unparalleled talent and be spellbound by the solo dance prowess!",
        "deadline":"9 April 2024",
        "moredetails":"https://docs.google.com/document/d/1m6F71TuREYZb3GyALq0NzS39zt9ijKq5510tCsap4f4/edit",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLSdTZcQ4cFFom-TEPnCAIUgIGQs6jTlpZ-z91R5XkMFOD_VWsQ/viewform"
    },
    {
        "id":3,
        "title":"Step Wars",
        "subtitle":"1 vs 1 Battle",
        "image":require("./assets/culturalEventPics/stepwar.png"),
        "url":"gvhb",
        "time":"12 April 2024",
        "fee":"₹ 200",
        "prize":"₹ 16k",
        "teamSize":"1 member",
        "desc":"Witness an ensemble of extraordinary solo dancers ignite the stage with mesmerizing performances. From hip-hop's rhythmic beats to contemporary dance's grace, each artist captivates with distinctive style, breathtaking choreography and sensational showmanship. Join us for a night of unparalleled talent and be spellbound by the solo dance prowess!",
        "deadline":"9 April 2024",
        "moredetails":"https://docs.google.com/document/d/18iYwwQpYAmv9F-GSp6eUkMdsXF1pQfJ77iJcMrEk2Tk/edit",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLScU6pjNcQIEmbSFxqG96j2LSbIVjDv_MMXOv6CCj7xm34-_SA/viewform"
    },
    {
        "id":4,
        "title":"Solo Serenade",
        "subtitle":"Solo Singing",
        "image":require("./assets/culturalEventPics/solosinging.png"),
        "url":"gvhb",
        "time":"13 April 2024",
        "fee":"₹ 150",
        "prize":"₹ 15.5k",
        "teamSize":"1 member",
        "desc":"Unleash your vocal prowess and take centre stage as we let you elevate your voice, captivate the audience, and compete for the title of the ultimate solo sensation. It's your time to shine, hit those high notes, share your unique sound and let the melody of your talent resonate through our hearts. Join us for a night of unforgettable performances and musical magic. Are you ready to be the solo star of the show? Tune in and turn up the excitement!",
        "deadline":"9 April 2024",
        "moredetails":"https://docs.google.com/document/d/16dK0SIC0Wy83pbftKNe8m0av0s-WzF4dGLujpJy5uBc/edit",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLSedmvzPVTGFh1K3NARJG9gbzwA91gs223Gh2cu_2C8I0foqOA/viewform"
    },
    {
        "id":5,
        "title":"Melodic Expendition",
        "subtitle":"Solo Instrument",
        "image":require("./assets/culturalEventPics/melodicexp.png"),
        "url":"gvhb",
        "time":"12 April 2024",
        "fee":"₹ 200",
        "prize":"₹ 16k",
        "teamSize":"1 member",
        "desc":"Embark on a Melodic Expedition, where solo instruments become sonic adventurers, creating enchanting melodies that resonate with your heartbeat. Get ready for a night of musical brilliance as each instrumentalist paints a unique sonic masterpiece on the stage. Join us for a symphony of discovery and creativity.",
        "deadline":"9 April 2024",
        "moredetails":"https://docs.google.com/document/d/1mbKVVTgMXMjNP2cq5ENXXg0zxwPjLxp-hzWLhCKuQQM/edit",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLScwWnabf5wW1yvqkmNGqTjTe_MJeYymCHnftygnFPrRqKNZ2g/viewform"
    },
    {
        "id":6,
        "title":"Rhythmic Rumble",
        "subtitle":"Battle Of Bands",
        "image":require("./assets/culturalEventPics/rythmicrumble.png"),
        "url":"gvhb",
        "time":"12 April 2024",
        "fee":"₹ 550",
        "prize":"₹ 45k",
        "teamSize":"4-8 members",
        "desc":"Enhance the impact of your music, captivating audiences and drawing them into the harmonious resonance of your melodies. Tune the souls of listeners to the enchanting vibrations of your strings, elevate heartbeats with each beat and ignite a visceral response that pulses through the crowd. Step into the spotlight with confidence, ready to showcase your skills and compete amongst the best.",
        "deadline":"9 April 2024",
        "moredetails":"https://docs.google.com/document/d/1x1rpoRxwg96si9Kl8RMALwODbt4bTT3a3gvaEMiQPJs/edit",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLSdqVaUrS6QcyZfL7uXo5PSIcPlt4XAuIJBK7HKi59spLvaBww/viewform"
    },
    {
        "id":7,
        "title":"Focus And Click",
        "subtitle":"Capture The Moment",
        "image":require("./assets/culturalEventPics/focusclick.png"),
        "url":"gvhb",
        "time":"Pre event",
        "fee":"NaN",
        "prize":"₹ 12k",
        "teamSize":"1 member",
        "desc":"Capture The Moment” is not just a contest; it is an exploration of the extraordinary in the ordinary, a celebration of the beauty that surrounds us every day. Embark on this photographic journey with us, where your lens transforms into a storyteller, encapsulating those cherished instances that define our shared human experience.",
        "deadline":"9 April 2024",
        "moredetails":"https://docs.google.com/document/d/19fc_DaoWzS6GI8FKBqRvcrDQhITM1phTKZoLeoSqPhY/edit",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLScHGNmGYW65hcl-ZmQKtRhx1OOdiow6UqNrIVywKtk9t8aN-g/viewform"
    },
    {
        "id":8,
        "title":"Reel Rapture",
        "subtitle":"Reel Making",
        "image":require("./assets/culturalEventPics/reel.png"),
        "url":"gvhb",
        "time":"Pre event",
        "fee":"NaN",
        "prize":"₹ 12k",
        "teamSize":"1 member",
        "desc":"Embark on a cinematic odyssey in our electrifying reel-making competition! Ignite your passion, weave mesmerizing tales, and dazzle with visual splendor. This is your chance to shine where every frame becomes a masterpiece. Join us in this exhilarating adventure, where creativity knows no bounds! Unleash your storytelling magic!",
        "deadline":"9 April 2024",
        "moredetails":"https://docs.google.com/document/d/1SKzvB8X_XmE5Qi_5yykjFyoS5PjVBGNC6EpU23D0tSs/edit",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLSfy083-0HYMpDq6PuJzMK0ssBOK8iIbuRMlZNhpte2dVCfXKg/viewform"
    },
    {
        "id":9,
        "title":"Radiant Stains",
        "subtitle":"Face Painting",
        "image":require("./assets/culturalEventPics/face.png"),
        "url":"gvhb",
        "time":"12 April 2024",
        "fee":"₹ 100",
        "prize":"₹ 13k",
        "teamSize":"2 members",
        "desc":"This Face Painting competition invites artists to harness the power of light and color. Whether with bold strokes or subtle impressions, join us in exploring where colors meet brilliance. Let your artwork shine in this celebration of expression!",
        "deadline":"9 April 2024",
        "moredetails":"https://docs.google.com/document/d/1HR3iFmfnD9N29eM18BpFTEd47I-r0Z5owsXVrP8Qe_0/edit",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLSdXkjBRkDv-83YthTvq8IPJA6t6olukRndgj_fYRuevwRubiw/viewform"
    },
    {
        "id":10,
        "title":"Tinker Tales",
        "subtitle":"Doodling",
        "image":require("./assets/culturalEventPics/tinker.png"),
        "url":"gvhb",
        "time":"12 April 2024",
        "fee":"₹ 100",
        "prize":"₹ 13k",
        "teamSize":"1 member",
        "desc":"Spark your creativity and ignite your artistic skills in our exciting doodle making contest. from cute and eccentric to bold and abstract, let your imagination run free and fingers doodle your way to the top This isn't just a contest; it's an enchanting celebration of limitless creativity, where your doodles transform into captivating tales.",
        "deadline":"9 April 2024",
        "moredetails":"https://docs.google.com/document/d/11VE8oT3Ub_-EVyU3EGcst3tDIaObsxa5cBUA-UxAOPk/edit",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLSeMUbpVQ_Nml2bwx0b9yx35rwjAO5Zvkhr6FCneUHiQw-6Uiw/viewform"
    },
    {
        "id":11,
        "title":"In-Quiz-Itive",
        "subtitle":"General Quiz",
        "image":require("./assets/culturalEventPics/quiz.png"),
        "url":"gvhb",
        "time":"14 April 2024",
        "fee":"₹ 100",
        "prize":"₹ 13k",
        "teamSize":"2 members",
        "desc":"Savyas brings to you a platform to test your expertise in the world of General Knowledge and to boost the spirit of quizzing in us. Rattle your brains and answer the questions at “In-Quiz-itive.",
        "deadline":"9 April 2024",
        "moredetails":"https://docs.google.com/document/d/1IeVYmwFGRQx-SMxeqOR1RCwDhR7CMNduTvSutc5Q5As/edit",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLScQLOpWF7Q0vRAnzqq1_nGnkVOwTFQnAWE3E_wP957U5ifJhQ/viewform"
    },
    {
        "id":12,
        "title":"Mela Quiz",
        "subtitle":"Entertainment & Literature Quiz",
        "image":require("./assets/culturalEventPics/melaquiz.png"),
        "url":"gvhb",
        "time":"12 April 2024",
        "fee":"₹ 100",
        "prize":"₹ 13k",
        "teamSize":"2 members",
        "desc":"Lights, Camera, Action… Saavyas brings to you an exciting dive into the world of MELA, where Music, Entertainment, Literature, and Arts converge in an electrifying showdown!. May it be your awe for James Bond or your love for The Beatles, your admiration for Shakespeare or your fascination for Van Gogh, there’s something for everyone at 'MELA QUIZ'",
        "deadline":"9 April 2024",
        "moredetails":"https://docs.google.com/document/d/1f3yMK-8x4OFqsESRJ5BWxmegYJt8TnnB-CIVtR1sZ_o/edit",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLSeqftius89FoCKQcP6q4bjwW9nv3_35riLfEaG1dUgVaOl8_g/viewform"
    },
    {
        "id":13,
        "title":"Shadows Of Morality",
        "subtitle":"Debate",
        "image":require("./assets/culturalEventPics/shadowmorality.png"),
        "url":"gvhb",
        "time":"14 April 2024",
        "fee":"₹ 200",
        "prize":"₹ 14.5k",
        "teamSize":"2 members",
        "desc":"Saavyas presents to you its Debate competition where your thoughts meet the platform to voice it out. Now is the time for your line of reasoning, rebuttals and team coordination to win exciting prizes.",
        "deadline":"9 April 2024",
        "moredetails":"https://docs.google.com/document/d/1bPMFcvuMFlph76fbWjRWhZ8F99_sfbh796FSp3WvZR0/edit",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLScbe3g6UMb9qW0OIodWjiDGlV3-lF8ChhNaDVhLSOgv_c26Tw/viewform"
    },
    {
        "id":14,
        "title":"JAM",
        "subtitle":"Just A Minute",
        "image":require("./assets/culturalEventPics/jam.png"),
        "url":"gvhb",
        "time":"12 April 2024",
        "fee":"₹ 50",
        "prize":"₹ 11k",
        "teamSize":"1 member",
        "desc":"Dive into thewhirlwind of wit and spontaneity at “Just A Minute”(JAM). Participants showcase their creativity and quick thinkingwith on-the-spot topics, aiming to dazzle in a heart-pounding 60 seconds. The finals guarantee an electrifying twist, delivering an unforgettable, high-energy celebration of expression that's bound to leave you breathless!",
        "deadline":"9 April 2024",
        "moredetails":"https://docs.google.com/document/d/1KGEY68tdsjfVMPJhW4Ly_nlJ1ozXnGGnYut1VK9Zbko/edit",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLScRCouJ1fbxM8eCO-0T07LMQ3U2_bKk6oeV8sH7lXgdkfdvbQ/viewform"
    },
    {
        "id":15,
        "title":"Verse Vortex",
        "subtitle":"Poetry Competition",
        "image":require("./assets/culturalEventPics/versevortex.png"),
        "url":"gvhb",
        "time":"14 April 2024",
        "fee":"₹ 100",
        "prize":"₹ 12.25k",
        "teamSize":"1 member",
        "desc":"Calling all poets and wordsmiths! Are you ready to let your creativity soar? Join us for our Poetry Competition - 'THE VERSE VORTEX' and immerse yourself in a world of lyrical beauty. Whether you're a seasoned poet or just starting your journey with verse, this competition is for you. Share your unique perspective, emotions, and stories through the power of poetry. Let your words ignite hearts and minds. Be part of a community united by the love of language and expression. Unleash your inner poet and join us on this enchanting journey.",
        "deadline":"9 April 2024",
        "moredetails":"https://docs.google.com/document/d/1u9OVnHcaglwTucOSLd3GBph46nrpVinr1A7Mo1lAEW0/edit",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLSfI-DInFZ5ehNB74E-Kt4dgLuIeGnTdf2sCx0pDkfDQLA1Q5Q/viewform"
    },
    {
        "id":16,
        "title":"Eras of Fashion",
        "subtitle":"Fashion Show",
        "image":require("./assets/culturalEventPics/fashion.png"),
        "url":"gvhb",
        "time":"13 April 2024",
        "fee":"₹ 650",
        "prize":"₹ 45k",
        "teamSize":"7-15 members",
        "desc":"Step into the grandeur of fashion history with our exclusive event showcasing the evolution of style from the medieval era to today's contemporary trends. Embark on a captivating journey through time as we celebrate the diverse cultures and global influences that have shaped fashion throughout the ages. From the splendour of Renaissance attire to the bold statements of the Roaring Twenties, And from the enchanting glamour of madhubala, to the ritziness of Cleopatra, experience the richness of fashion heritage spanning across continents and centuries.",
        "deadline":"9 April 2024",
        "moredetails":"https://docs.google.com/document/d/1ALEBoaFwGCGNczwgPYO-N3g7TYk7YB3JM3jNMxaV4uU/edit",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLSfPbiLPybAX9w7rf40DYzUeRFOMzH3FoCyj9GF_1k4vK0eCsw/viewform"
    },
    {
        "id":17,
        "title":"Mr and Miss Saavyas",
        "subtitle":"Mr and Miss Saavyas",
        "image":require("./assets/culturalEventPics/mrmssaavyas.png"),
        "url":"gvhb",
        "time":"13 April 2024",
        "fee":"₹ 100",
        "prize":"₹ 16k",
        "teamSize":"1 member",
        "desc":"Get ready to embark on a journey of elegance, and charm. The esteemed titles of Mr. and Miss Saavyas go far beyond the glitz and glamour of the stage. It is a recognition of the refined qualities that lie within each individual. They symbolize the embodiment of grace, distinction, and the celebration of individuality. It is a canvas for you to paint your uniqueness and shine like the star you truly are. Brace yourself to bask in the limelight and exhibit your exceptional charm, talent, and wit!",
        "deadline":"9 April 2024",
        "moredetails":"https://docs.google.com/document/d/1OJA9LJTRGFNyQ5Sfn-5wZuWvzBwtr5O8PIJtWh0-oKk/edit",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLSdifhZE4wyP4Di-CP3SfbP5EsFvg5apUPaoftSvrteiaxX8qA/viewform"
    },
    {
        "id":18,
        "title":"Humor Havoc",
        "subtitle":"Stand-Up",
        "image":require("./assets/culturalEventPics/humor.png"),
        "url":"gvhb",
        "time":"12 April 2024",
        "fee":"₹ 200",
        "prize":"₹ 17.5k",
        "teamSize":"1 member",
        "desc":"Calling all brave souls with jokes spicier than a Sichuan hotpot! Step into Humor Havoc, where we're on the hunt for the town's funniest individuals to unleash their comedic fury. Got punchlines that pack a punch and wit that wows? Simmer down your anxieties, get ready to boil over with laughter, and answer the stage's call!",
        "deadline":"9 April 2024",
        "moredetails":"https://docs.google.com/document/d/17ou1lf5gOcPbf72i2kzR9Mqe3ziLJHOsnfuoD0_72pA/edit",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLSeMUNuvKwNU6fIMkisn81n0vX8NqJtFcn2Qfa2IN-8SkvVnfA/viewform"
    },
    {
        "id":19,
        "title":"Stains Odyssey",
        "subtitle":"Treasure Hunt",
        "image":require("./assets/culturalEventPics/stain.png"),
        "url":"gvhb",
        "time":"12 April 2024",
        "fee":"₹ 100",
        "prize":"₹ 33k",
        "teamSize":"3 members",
        "desc":"Buckle up you are behind a winner. Prepare to delve into a world where every blotch, smear, and blemish holds a story waiting to be discovered. Traverse through forgotten corridors, decipher cryptic clues hidden within the fabric of time, and unearth the secrets concealed beneath layers of history. Join us as we embark on this odyssey of stains, where each mark tells a tale and every discovery unveils a new chapter in the epic saga of the Stains Odyssey. Dare to journey into the unknown, where adventure awaits around every corner and the truth lies within the stains.",
        "deadline":"9 April 2024",
        "moredetails":"https://docs.google.com/document/d/1uSNAwR64ZD3fnVBSkHKaaPf2XMQr0vkuinGhrRkf1m0/edit",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLSdv7dp1-2rk1VjV53rnbjsZJfCVo54tfUyQUdiH54HYPgAIDg/viewform"
    },
    {
        "id":20,
        "title":"Enigma On Stage",
        "subtitle":"Stage Play",
        "image":require("./assets/culturalEventPics/engima.png"),
        "url":"gvhb",
        "time":"12 April 2024",
        "fee":"₹ 550",
        "prize":"₹ 45k",
        "teamSize":"3 or more members",
        "desc":"Enigma on Stage”, a captivating One-Act Play competition that blends the beauty of theatre with mystery and intrigue. The stage comes alive with a palpable air of suspense, inviting the audience into a world where the art of storytelling converges with the enigmatic allure of the unknown. The one-act format intensifies the impact, ensuring that every moment is laden with significance.",
        "deadline":"9 April 2024",
        "moredetails":"https://docs.google.com/document/d/1jPFsa0pd7de0-skY3wgoYidJRM_hP8rC_pgxuGk35P4/edit",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLScp2mqjxq-f7WbF6OyhZxJSmYxNlils1bZI1K7x3FVq6sLS5w/viewform"
    },
    {
        "id":21,
        "title":"Arcade",
        "subtitle":"Esports",
        "image":require("./assets/culturalEventPics/arcade.png"),
        "url":"gvhb",
        "time":"12 ,13 ,14 April 2024",
        "fee":"₹ 350",
        "prize":"To be disclosed soon",
        "teamSize":"3 or more members",
        "desc":"Get ready to witness the ultimate clash of digital champions at the ARCADE! Join us for a heartpounding spectacle featuring intense battles in Valorant, exhilarating showdowns in BGMI, strategic duels in Clash Royale, and hilarious chaos in Stumble Guys. Brace yourself for a gaming extravaganza like no other, where skill, strategy, and sheer entertainment collide in an electrifying arena of competition. Don't miss out on the action secure your spot now and be part of esports history!",
        "deadline":"9 April 2024",
        "moredetails":"https://docs.google.com/document/d/1bNJhldmfw1RkCUNtZFo7x2V1YyBpRB_bGnnHlXIWYhw/edit",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLSeoAj4eJLCThCU-jMiRk-xakJVPI6vFPjCPDvahTr6E-Wb2EA/viewform"
    }

]