export default carouselItems =  [
    {
        "id":1,
        "title":"Pix-A-Thon",
        "subtitle":"Hack, Hustle and Harmonize!",
        "image":require("./assets/techEventPics/pixathon.png"),
        "url":"fgv",
        "time":"12-13 April 2024",
        "fee":"₹200",
        "prize":"₹ 40k",
        "teamSize":"2-3 members",
        "desc":"Dust off your laptops,assemble your dream team, and prepare to embark on an epic hacking adventure at SAAVYAS’24. Get ready for a 24 hour marathon of creativity and innovation fueled by caffeine and collaboration.",
        "deadline":"9 April 2024",
        "moredetails":"https://docs.google.com/document/d/16OOiiOM4iFHLdnPhMND1RPZtTZLAAKceKWs5ttTExAI/edit",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLSf5c0obrX_yZ3OXLlKn8FgUiuUy_Zpq3-DMUoroMwDPSQgq4g/viewform"
    },
    {
        "id":2,
        "title":"EleKtron",
        "subtitle":"Where circuits converge and solutions emerge",
        "image":require("./assets/techEventPics/elektron.png"),
        "url":"gvhb",
        "time":"14 April 2024",
        "fee":"₹200",
        "prize":"₹ 26.5k",
        "teamSize":"2 members",
        "desc":"Where electrons dance, circuits come to life. Embark on a dynamic journey of circuit design and debugging, where challenges are currents pushing you towards solutions. Join the convergence of creativity and precision, sculpting electrical pathways. In this electrifying domain, innovation sparks, and circuits breathe with life-changing solutions.",
        "deadline":"9 April 2024",
        "moredetails":"https://docs.google.com/document/d/1oUDu43-A7I0EkAOxu6FnUdazArTcjDMoaNBfUMjvCFc/edit",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLSfCS-tHxsKCqi5tSV8g82vWlbNRj30ffZF0Hrq4AEb0THoP4A/viewform"
    },
    {
        "id":3,
        "title":"KeyBlitz",
        "subtitle":"Where circuits converge and solutions emerge",
        "image":require("./assets/techEventPics/keyblitz.png"),
        "url":"gvhb",
        "time":"13 April 2024",
        "fee":" ₹50",
        "prize":"₹ 11k",
        "teamSize":"1 member",
        "desc":"An exciting contest that gauges more than just raw wpm-KeyBlitz! Compete through a series of stages, each posing a different challenge,where it’s not just about the high speed you can pull up but also where skill plus strategy reigns supreme. Do you have what it takes to win it all?",
        "deadline":"9 April 2024",
        "moredetails":"https://docs.google.com/document/d/11SVsxTZuT1tVQo0fhjxP4Mq9sUT8OIBY4Gk5GoRGRmo/edit",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLSeo88cVPrTLEsdjmzRhL3BYBsqlXhgxQ5XxOSOyp7udjNbx-g/viewform"
    },
    {
        "id":4,
        "title":"The Lost Pixel",
        "subtitle":"A single Pixel holds the KEY",
        "image":require("./assets/techEventPics/thelostpixel.png"),
        "url":"gvhb",
        "time":"11 April 2024",
        "fee":" ₹50",
        "prize":"₹ 25k",
        "teamSize":"1 member",
        "desc":"Are you a coder and also an explorer? We have a perfect match in heaven for you! Join our mind bending online adventure. Crack cryptic clues, test your tech skills,and unearth hidden secrets. Up for the ultimate digital quest? We even have a sneak peek to ignite your curiosity. Divein!",
        "deadline":"9 April 2024",
        "moredetails":"https://docs.google.com/document/d/165546Ik2IJMhfZl68AljPgrWMJQ6lkgcLC96jANWf0U/edit",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLSc8CkI4Xh8wTT2sU226MakKNN5boi3TfDXl9xWyrzRkfYjJ7A/viewform"
    },
    {
        "id":5,
        "title":"Prompt-a-thon",
        "subtitle":"Prompt Engineering",
        "image":require("./assets/techEventPics/promptathon.png"),
        "url":"gvhb",
        "time":"14 April 2024",
        "fee":"₹ 100",
        "prize":"₹ 25k",
        "teamSize":"1-4 members",
        "desc":"Embark on an exhilarating journey with our cutting-edge contest, meticulously crafted to elevate your technical prowess and ignite your creative problem-solving flair.In this thrilling two-round showdown, push your boundaries by crafting compelling prompts and harnessing the power of generative AI to recreate images with unparalleled precision.Refine your skills, flaunt your talent, and vie for victory!",
        "deadline":"9 April 2024",
        "moredetails":"https://docs.google.com/document/d/1x9EUlrxNLhtGTo6oniOvZNgAncJUVDJlQmxgMORuDl8/edit",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLSe_4r26AETmcGWXvukyH1k2u5hFj8tW0WfwN300z3u0yo3kaA/viewform"
    },
    {
        "id":6,
        "title":"BitBash",
        "subtitle":"Code Clash Extravaganza",
        "image":require("./assets/techEventPics/bitbash.png"),
        "url":"gvhb",
        "time":"12 April 2024",
        "fee":"₹ 250",
        "prize":"₹ 30k",
        "teamSize":"1-2 members",
        "desc":"Calling all code warriors and logic lords! We are bringing to you a mind-bending Competitive Programming Challenge that will push your coding skills to the extremes and leave you feeling like a wizard with keyboard.",
        "deadline":"9 April 2024",
        "moredetails":"https://docs.google.com/document/d/1QyMbrMrrpOvn5aZH5rMb9S5WkxSgiUR7cWXFKJVdEig/edit",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLSex7ovsdHxjdLBsazqHtwwsfImSUGERjNmTWlHkEiOoZ8ZVsg/viewform"
    },
    {
        "id":7,
        "title":"Pixel Precision",
        "subtitle":"Trackmasters Challenge",
        "image":require("./assets/techEventPics/pixelprecision.png"),
        "url":"gvhb",
        "time":"12 April 2024",
        "fee":"NaN",
        "prize":"₹ 20k & VOUCHER: ₹ 20k",
        "teamSize":"2-3 members",
        "desc":"Gear up for Pixel Race, where robots rev their engines in a high-speed dash through pixelated tracks. With lightning reflexes and sleek designs, they zoom past obstacles and rivals. It's a heart-pounding display of speed and strategy, where victory awaits the boldest bots in the pixelated arena!",
        "deadline":"9 April 2024",
        "moredetails":"https://drive.google.com/file/d/1Q26G9cyGwYs-SHlrLlGOQwdyd0w28Atq/view",
        "register":"https://drive.google.com/file/d/1Q26G9cyGwYs-SHlrLlGOQwdyd0w28Atq/view"
    },
    {
        "id":8,
        "title":"Robo Rumbling",
        "subtitle":"Let the Bot be the Goat",
        "image":require("./assets/techEventPics/roborumbling.png"),
        "url":"gvhb",
        "time":"13, 14 April 2024",
        "fee":"₹ 300",
        "prize":"₹ 16k & VOUCHER: ₹ 20k",
        "teamSize":"2 members",
        "desc":"Do you want your Bot to be the next Goat? It's time to make your dream a reality. SAAVYAS’24 is ready to proudly present to you RoboSoccer where the robo beasts collide to be crowned the ultimate soccerbot.",
        "deadline":"9 April 2024",
        "moredetails":"https://drive.google.com/file/d/1EzivdZj-mbt4RvQbRU6PSVYdhQsob2--/view",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLScHnY6yNhl9-vYXU8xSaq67NwpUSR8yNyWYB_SJnCELYS-z_A/viewform"
    },
    {
        "id":9,
        "title":"Pixel Clench",
        "subtitle":"Pixel Clench",
        "image":require("./assets/techEventPics/pixelclench.png"),
        "url":"gvhb",
        "time":"12, 13, 14 April 2024",
        "fee":"NaN",
        "prize":"₹ 25k",
        "teamSize":"1-2 members",
        "desc":"Witness the adrenaline-fueled clash of robots in a pixelated arena. With each move, they dodge obstacles and seize victory! It's the ultimate showdown of mechanical prowess and innovation. Don't blink, or you'll miss the action-packed spectacle of Pixel Clench!",
        "deadline":"9 April 2024",
        "moredetails":"https://drive.google.com/file/d/1mIJHQVnGyrfJ3wK74C2myPrhl7Hc1pJ6/view",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLSdsXdGOOIv5ViM3n7cnKnYF4wDlLQ-1FghmzBIx1Fovq_Y8cg/viewform"
    },
    {
        "id":10,
        "title":"Pixelated Propellers’\n Showdown",
        "subtitle":"Unleash the Drone Maverick in You!",
        "image":require("./assets/techEventPics/pixelatedshow.png"),
        "url":"gvhb",
        "time":"12 ,13 ,14 April 2024",
        "fee":"NaN",
        "prize":"₹ 5k & VOUCHER: ₹ 20k",
        "teamSize":"2-4 members",
        "desc":"Prepare to defy gravity and ignite the skies at SAAVYAS, where adrenaline meets altitude! Join us for the ultimate Drone Race, an electrifying spectacle that takes your passion for technology to new heights.Showcase your piloting prowess as you command your drone through twists, turns, and exhilarating aerial maneuvers.",
        "deadline":"9 April 2024",
        "moredetails":"https://drive.google.com/file/d/1qLzISETT5K5SpDXe19KVQFEvA1IGuXWC/view",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLSdsXdGOOIv5ViM3n7cnKnYF4wDlLQ-1FghmzBIx1Fovq_Y8cg/viewform"
    },
    {
        "id":11,
        "title":"Case Closed",
        "subtitle":"Cracking the code to corporate success, one slide at a time.",
        "image":require("./assets/techEventPics/caseclosed.png"),
        "url":"gvhb",
        "time":"14 April 2024",
        "fee":"₹ 200",
        "prize":"₹ 26k",
        "teamSize":"1-3 members",
        "desc":"Embark on a journey of innovation and strategic thinking to showcase your prowess in tackling real world case studies. Amplify your problem-solving talent by crafting unique solutions and presenting them with flair. It's not just about answers, it’s about the art of turning challenges into opportunities. Join us to elevate your case-solving game.",
        "deadline":"9 April 2024",
        "moredetails":"https://docs.google.com/document/d/1V4irkGgLhMplsoF2eEFDSVIThvDgBi05ppbyMZA2qY8/edit",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLSdKKN-Ahy0VldbYjICquIxKPcR24wjQqCvSu509rrnUNsnhjw/viewform"
    },
    {
        "id":12,
        "title":"Quantum Maze \nExplorer",
        "subtitle":"Maze Solving Robot",
        "image":require("./assets/techEventPics/quantummaze.png"),
        "url":"gvhb",
        "time":"13 April 2024",
        "fee":"₹ 250",
        "prize":"₹ 11k & VOUCHER: ₹ 20k",
        "teamSize":"2-8 members",
        "desc":"Prepare to dive into the depths of innovation and engineering with Maze-Runner, the Maze Solving Robot Competition! Watch as robots race through intricate mazes, using their sensors, motors, and brains to navigate and make quick decisions while avoiding obstacles.",
        "deadline":"9 April 2024",
        "moredetails":"https://docs.google.com/document/d/1QDO56EX0HYdsorv0wUE6bkdk1_VR-hkrB_fvISAJrQ4/edit",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLSdTUI9JZeUAmTB9q49SY8yQILDjB-YH_T1T6c2cF5IykrLIHw/viewform"
    },
    {
        "id":13,
        "title":"Profit Pulse",
        "subtitle":"Maze Solving Robot",
        "image":require("./assets/techEventPics/profitpulse.png"),
        "url":"gvhb",
        "time":"Pre event",
        "fee":"Nan",
        "prize":"₹ 30k",
        "teamSize":"1 member",
        "desc":"Profit Pulse immerses you in the dynamic world of virtual finance, transforming novices into savvy traders. Dive into our virtual stock market, where strategic decisions yield prosperity. With real-time simulations and risk-free trades, hone your financial acumen. Trade smart, adapt to market trends, and prosper with virtual riches on the ProfitPulse platform.",
        "deadline":"8 April 2024",
        "moredetails":"https://docs.google.com/document/d/12EvGbnmnh2li-c2iLtFQDyMi8jh_UgYEZtTCGm5oMM8/edit",
        "register":"https://docs.google.com/forms/d/e/1FAIpQLSctm13F1Iq_RFL-v07O44iWKugyb7On5Qq5fZioKJ7WOp3sXw/viewform"
    },
]